// <auto-generated />
using System;
using BleemSync.Central.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BleemSync.Central.Web.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BleemSync.Central.Data.Models.EsrbRatingDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("EsrbRatingDescriptors");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.GameGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PegiRatingDescriptor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PegiRatingDescriptors");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.Art", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DiscId");

                    b.Property<string>("File");

                    b.Property<int?>("GameId");

                    b.Property<bool>("IsGreatestHits");

                    b.Property<decimal>("Rating");

                    b.Property<int>("RatingVoteCount");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("DiscId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayStation_Art");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.Disc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DiscNumber");

                    b.Property<string>("Fingerprint");

                    b.Property<int?>("GameId");

                    b.Property<int>("TrackCount");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PlayStation_Discs");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AnalogCompatible");

                    b.Property<DateTime>("DateReleased");

                    b.Property<string>("Description");

                    b.Property<string>("Developer");

                    b.Property<bool>("DigitalCompatible");

                    b.Property<int>("EsrbRating");

                    b.Property<string>("Fingerprint");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("LightGunCompatible");

                    b.Property<bool>("LinkCableCompatible");

                    b.Property<int>("MemoryCardBlockCount");

                    b.Property<bool>("MultitapCompatible");

                    b.Property<bool>("OfficiallyLicensed");

                    b.Property<int>("PegiRating");

                    b.Property<string>("Players");

                    b.Property<string>("Publisher");

                    b.Property<int>("Region");

                    b.Property<string>("Title");

                    b.Property<string>("Version");

                    b.Property<bool>("VibrationCompatible");

                    b.HasKey("Id");

                    b.ToTable("PlayStation_Games");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.GameRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApprovedById");

                    b.Property<DateTime?>("ApprovedOn");

                    b.Property<int>("GameId");

                    b.Property<string>("RejectedById");

                    b.Property<DateTime?>("RejectedOn");

                    b.Property<int>("RevisedGameId");

                    b.Property<string>("SubmittedById");

                    b.Property<DateTime?>("SubmittedOn");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("GameId");

                    b.HasIndex("RejectedById");

                    b.HasIndex("SubmittedById");

                    b.ToTable("PlayStation_GameRevisions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");


                    b.ToTable("ApplicationUser");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.EsrbRatingDescriptor", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game")
                        .WithMany("EsrbRatingDescriptors")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.GameGenre", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PegiRatingDescriptor", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game")
                        .WithMany("PegiDescriptors")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.Art", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Disc", "Disc")
                        .WithMany("Art")
                        .HasForeignKey("DiscId");

                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game", "Game")
                        .WithMany("Art")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.Disc", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game", "Game")
                        .WithMany("Discs")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("BleemSync.Central.Data.Models.PlayStation.GameRevision", b =>
                {
                    b.HasOne("BleemSync.Central.Data.Models.ApplicationUser", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("BleemSync.Central.Data.Models.PlayStation.Game")
                        .WithMany("Revisions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BleemSync.Central.Data.Models.ApplicationUser", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById");

                    b.HasOne("BleemSync.Central.Data.Models.ApplicationUser", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
