// <auto-generated />
using System;
using BleemSync.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BleemSync.Data.Migrations
{
    [DbContext(typeof(MenuDatabaseContext))]
    [Migration("20190115023630_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("BleemSync.Data.Models.Disc", b =>
                {
                    b.Property<int>("DiscId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("DISC_ID");

                    b.Property<string>("DiscBasename")
                        .HasColumnName("BASENAME");

                    b.Property<int>("DiscNumber")
                        .HasColumnName("DISC_NUMBER");

                    b.Property<int>("GameId")
                        .HasColumnName("GAME_ID");

                    b.HasKey("DiscId");

                    b.HasIndex("GameId");

                    b.ToTable("DISC");
                });

            modelBuilder.Entity("BleemSync.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("GAME_ID");

                    b.Property<string>("GameManualQrImage")
                        .HasColumnName("GAME_MANUAL_QR_IMAGE");

                    b.Property<string>("LinkGameId")
                        .HasColumnName("LINK_GAME_ID");

                    b.Property<int>("Players")
                        .HasColumnName("PLAYERS");

                    b.Property<int?>("Position")
                        .HasColumnName("POSITION");

                    b.Property<string>("Publisher")
                        .HasColumnName("PUBLISHER_NAME");

                    b.Property<string>("RatingImage")
                        .HasColumnName("RATING_IMAGE");

                    b.Property<string>("Title")
                        .HasColumnName("GAME_TITLE_STRING");

                    b.Property<int>("Year")
                        .HasColumnName("RELEASE_YEAR");

                    b.HasKey("Id");

                    b.ToTable("GAME");
                });

            modelBuilder.Entity("BleemSync.Data.Models.Language", b =>
                {
                    b.Property<string>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("LANGUAGE_ID");

                    b.Property<string>("DefaultValue")
                        .HasColumnName("DEFAULT_VALUE");

                    b.Property<string>("Value")
                        .HasColumnName("VALUE");

                    b.HasKey("LanguageId");

                    b.ToTable("LANGUAGE_SPECIFIC");
                });

            modelBuilder.Entity("BleemSync.Data.Models.Disc", b =>
                {
                    b.HasOne("BleemSync.Data.Models.Game", "Game")
                        .WithMany("Discs")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
