#!/bin/sh
#
#  Copyright 2019 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################
# Credits injection script
# ModMyClassic.com / https://discordapp.com/invite/8gygsrw
###############################################################################

source /var/volatile/bleemsync.cfg
[ -f "$bleemsync_path/etc/bleemsync/SUP/license/head_credits.lic" ] && \
    cat "$bleemsync_path/etc/bleemsync/SUP/license/head_credits.lic" && echo
find "${VOL_GAADATA}" -name "*.lic" -exec cat {} \;
[ -f "$bleemsync_path/etc/bleemsync/SUP/license/tail_credits.lic" ] && \
    echo && cat "$bleemsync_path/etc/bleemsync/SUP/license/tail_credits.lic"
