-- Migrate tables
ALTER TABLE GAME
ADD COLUMN "POSITION" INTEGER NULL;
ALTER TABLE "GAME" RENAME TO "MENU_ENTRIES";
CREATE VIEW GAME AS SELECT * FROM MENU_ENTRIES ORDER BY POSITION, GAME_TITLE_STRING;
-- Simulate EF migration
CREATE TABLE "__EFMigrationsHistory" ( "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY, "ProductVersion" TEXT NOT NULL );
INSERT INTO __EFMigrationsHistory VALUES ("20190115023630_Seed", "2.1.1-rtm-30846");
