#!/bin/bash
#
#  Copyright 2019 ModMyClassic (https://modmyclassic.com/license)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
###############################################################################
# Recursive Existing Files Overmount Script
# ModMyClassic.com / https://discordapp.com/invite/8gygsrw
###############################################################################

IFS='\n'
while read -r rel_file; do
  rel_file="${rel_file#$1/}"
  if [ -f "$2/${rel_file}" ]; then
    mount -o bind "$1/${rel_file}" "$2/${rel_file}"
  fi
done < <(find "$1" -type f)
